import type { SchemaTable } from "@/types"

/** Complete schema documentation for the gitmem SQLite database. */
export const SCHEMA: SchemaTable[] = [
  {
    name: "commits",
    description: "Core commit metadata and LLM enrichment results",
    virtual: false,
    columns: [
      {
        name: "hash",
        type: "TEXT",
        primary_key: true,
        not_null: true,
        description: "SHA-1 commit hash",
      },
      {
        name: "author_name",
        type: "TEXT",
        primary_key: false,
        not_null: true,
        description: "Author display name",
      },
      {
        name: "author_email",
        type: "TEXT",
        primary_key: false,
        not_null: true,
        description: "Author email address",
      },
      {
        name: "committed_at",
        type: "TEXT",
        primary_key: false,
        not_null: true,
        description: "ISO 8601 commit timestamp",
      },
      {
        name: "message",
        type: "TEXT",
        primary_key: false,
        not_null: true,
        description: "Full commit message",
      },
      {
        name: "classification",
        type: "TEXT",
        primary_key: false,
        not_null: false,
        description:
          "LLM-assigned classification (bug-fix, feature, refactor, docs, chore, perf, test, style)",
      },
      {
        name: "summary",
        type: "TEXT",
        primary_key: false,
        not_null: false,
        description: "LLM-generated 1-2 sentence summary",
      },
      {
        name: "enriched_at",
        type: "TEXT",
        primary_key: false,
        not_null: false,
        description: "ISO 8601 timestamp of when enrichment was performed",
      },
      {
        name: "model_used",
        type: "TEXT",
        primary_key: false,
        not_null: false,
        description: "Model identifier used for enrichment",
      },
    ],
  },
  {
    name: "commit_files",
    description: "Files changed within each commit",
    virtual: false,
    columns: [
      {
        name: "commit_hash",
        type: "TEXT",
        primary_key: true,
        not_null: true,
        description: "FK to commits.hash",
      },
      {
        name: "file_path",
        type: "TEXT",
        primary_key: true,
        not_null: true,
        description: "Repository-relative file path",
      },
      {
        name: "change_type",
        type: "TEXT",
        primary_key: false,
        not_null: true,
        description: "Git change type (A=added, M=modified, D=deleted)",
      },
      {
        name: "additions",
        type: "INTEGER",
        primary_key: false,
        not_null: false,
        description: "Lines added (default 0)",
      },
      {
        name: "deletions",
        type: "INTEGER",
        primary_key: false,
        not_null: false,
        description: "Lines deleted (default 0)",
      },
      {
        name: "lines_of_code",
        type: "INTEGER",
        primary_key: false,
        not_null: false,
        description:
          "Non-blank lines of code at this commit (NULL = unmeasured, 0 = skipped/binary/deleted)",
      },
      {
        name: "indent_complexity",
        type: "REAL",
        primary_key: false,
        not_null: false,
        description:
          "Sum of indentation levels across all lines (NULL = unmeasured, 0 = skipped)",
      },
      {
        name: "max_indent",
        type: "INTEGER",
        primary_key: false,
        not_null: false,
        description:
          "Maximum indentation level seen (NULL = unmeasured, 0 = skipped)",
      },
    ],
  },
  {
    name: "file_stats",
    description:
      "Aggregated per-file change statistics across all enriched commits",
    virtual: false,
    columns: [
      {
        name: "file_path",
        type: "TEXT",
        primary_key: true,
        not_null: true,
        description: "Repository-relative file path",
      },
      {
        name: "total_changes",
        type: "INTEGER",
        primary_key: false,
        not_null: true,
        description: "Total distinct commits touching this file",
      },
      {
        name: "bug_fix_count",
        type: "INTEGER",
        primary_key: false,
        not_null: true,
        description: "Number of bug-fix commits",
      },
      {
        name: "feature_count",
        type: "INTEGER",
        primary_key: false,
        not_null: true,
        description: "Number of feature commits",
      },
      {
        name: "refactor_count",
        type: "INTEGER",
        primary_key: false,
        not_null: true,
        description: "Number of refactor commits",
      },
      {
        name: "docs_count",
        type: "INTEGER",
        primary_key: false,
        not_null: true,
        description: "Number of docs commits",
      },
      {
        name: "chore_count",
        type: "INTEGER",
        primary_key: false,
        not_null: true,
        description: "Number of chore commits",
      },
      {
        name: "perf_count",
        type: "INTEGER",
        primary_key: false,
        not_null: true,
        description: "Number of perf commits",
      },
      {
        name: "test_count",
        type: "INTEGER",
        primary_key: false,
        not_null: true,
        description: "Number of test commits",
      },
      {
        name: "style_count",
        type: "INTEGER",
        primary_key: false,
        not_null: true,
        description: "Number of style commits",
      },
      {
        name: "first_seen",
        type: "TEXT",
        primary_key: false,
        not_null: true,
        description: "ISO 8601 date of earliest commit",
      },
      {
        name: "last_changed",
        type: "TEXT",
        primary_key: false,
        not_null: true,
        description: "ISO 8601 date of most recent commit",
      },
      {
        name: "total_additions",
        type: "INTEGER",
        primary_key: false,
        not_null: true,
        description: "Total lines added across all commits",
      },
      {
        name: "total_deletions",
        type: "INTEGER",
        primary_key: false,
        not_null: true,
        description: "Total lines deleted across all commits",
      },
      {
        name: "current_loc",
        type: "INTEGER",
        primary_key: false,
        not_null: false,
        description: "Lines of code from the most recent commit with data",
      },
      {
        name: "current_complexity",
        type: "REAL",
        primary_key: false,
        not_null: false,
        description:
          "Indentation complexity from the most recent commit with data",
      },
      {
        name: "avg_complexity",
        type: "REAL",
        primary_key: false,
        not_null: false,
        description:
          "Average indentation complexity across all measured commits",
      },
      {
        name: "max_complexity",
        type: "REAL",
        primary_key: false,
        not_null: false,
        description:
          "Maximum indentation complexity across all measured commits",
      },
    ],
  },
  {
    name: "file_contributors",
    description: "Per-file contributor commit counts",
    virtual: false,
    columns: [
      {
        name: "file_path",
        type: "TEXT",
        primary_key: true,
        not_null: true,
        description: "Repository-relative file path",
      },
      {
        name: "author_name",
        type: "TEXT",
        primary_key: false,
        not_null: true,
        description: "Contributor display name",
      },
      {
        name: "author_email",
        type: "TEXT",
        primary_key: true,
        not_null: true,
        description: "Contributor email address",
      },
      {
        name: "commit_count",
        type: "INTEGER",
        primary_key: false,
        not_null: true,
        description: "Number of commits by this contributor to this file",
      },
    ],
  },
  {
    name: "file_coupling",
    description: "Co-change frequency between file pairs",
    virtual: false,
    columns: [
      {
        name: "file_a",
        type: "TEXT",
        primary_key: true,
        not_null: true,
        description: "First file path (lexicographically smaller)",
      },
      {
        name: "file_b",
        type: "TEXT",
        primary_key: true,
        not_null: true,
        description: "Second file path (lexicographically larger)",
      },
      {
        name: "co_change_count",
        type: "INTEGER",
        primary_key: false,
        not_null: true,
        description: "Number of commits where both files changed together",
      },
    ],
  },
  {
    name: "batch_jobs",
    description: "Tracks Anthropic Message Batches API job status",
    virtual: false,
    columns: [
      {
        name: "batch_id",
        type: "TEXT",
        primary_key: true,
        not_null: true,
        description: "Anthropic batch job ID",
      },
      {
        name: "status",
        type: "TEXT",
        primary_key: false,
        not_null: true,
        description: "Job status (submitted, processing, ended)",
      },
      {
        name: "request_count",
        type: "INTEGER",
        primary_key: false,
        not_null: true,
        description: "Total requests in the batch",
      },
      {
        name: "succeeded_count",
        type: "INTEGER",
        primary_key: false,
        not_null: true,
        description: "Number of successfully processed requests",
      },
      {
        name: "failed_count",
        type: "INTEGER",
        primary_key: false,
        not_null: true,
        description: "Number of failed requests",
      },
      {
        name: "submitted_at",
        type: "TEXT",
        primary_key: false,
        not_null: true,
        description: "ISO 8601 submission timestamp",
      },
      {
        name: "completed_at",
        type: "TEXT",
        primary_key: false,
        not_null: false,
        description: "ISO 8601 completion timestamp",
      },
      {
        name: "model_used",
        type: "TEXT",
        primary_key: false,
        not_null: true,
        description: "Model identifier used for the batch",
      },
    ],
  },
  {
    name: "metadata",
    description: "Key-value store for index metadata (last run, model used)",
    virtual: false,
    columns: [
      {
        name: "key",
        type: "TEXT",
        primary_key: true,
        not_null: true,
        description: "Metadata key",
      },
      {
        name: "value",
        type: "TEXT",
        primary_key: false,
        not_null: true,
        description: "Metadata value",
      },
    ],
  },
  {
    name: "commits_fts",
    description:
      "FTS5 full-text search index over commit messages, classifications, and summaries",
    virtual: true,
    columns: [
      {
        name: "hash",
        type: "TEXT",
        primary_key: false,
        not_null: false,
        description: "Commit hash (UNINDEXED, stored but not searchable)",
      },
      {
        name: "message",
        type: "TEXT",
        primary_key: false,
        not_null: false,
        description: "Commit message (searchable)",
      },
      {
        name: "classification",
        type: "TEXT",
        primary_key: false,
        not_null: false,
        description: "LLM-assigned classification (searchable)",
      },
      {
        name: "summary",
        type: "TEXT",
        primary_key: false,
        not_null: false,
        description: "LLM-generated summary (searchable)",
      },
    ],
  },
]
